import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { QueryProvider } from '@/infrastructure/query/providers/query.providers';
import LocalizationProvider from '@/infrastructure/i18n/providers/language.providers';
import { ThemeProvider } from '@/infrastructure/theme/provider/theme.provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Chat App',
  description: 'Generated by create chat app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="mdl-js" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LocalizationProvider>
          <ThemeProvider>
            <QueryProvider devtools={process.env.NODE_ENV === 'development'}>
              {children}
            </QueryProvider>
          </ThemeProvider>
        </LocalizationProvider>
      </body>
    </html>
  );
}
